config/routes.rb
Rails.application.routes.draw do
  resources :meters

  root 'meters#index'

end

app/models/meter.rb
class Meter < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meters_controller.rb
class MetersController < ApplicationController
  before_action :set_meter, only: %i[show edit update destroy]

  # GET /meters
  # GET /meters.json
  def index
    @meters = Meter.all
  end

  # GET /meters/1
  # GET /meters/1.json
  def show; end

  # GET /meters/new
  def new
    @meter = Meter.new
  end

  # GET /meters/1/edit
  def edit; end

  # POST /meters
  # POST /meters.json
  def create
    @meter = Meter.new(meter_params)

    respond_to do |format|
      if @meter.save
        format.html { redirect_to @meter, notice: 'Meter was successfully created.' }
        format.json { render :show, status: :created, location: @meter }
      else
        format.html { render :new }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meters/1
  # PATCH/PUT /meters/1.json
  def update
    respond_to do |format|
      if @meter.update(meter_params)
        format.html { redirect_to @meter, notice: 'Meter was successfully updated.' }
        format.json { render :show, status: :ok, location: @meter }
      else
        format.html { render :edit }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meters/1
  # DELETE /meters/1.json
  def destroy
    @meter.destroy
    respond_to do |format|
      format.html { redirect_to meters_url, notice: 'Meter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meter
    @meter = Meter.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def meter_params
    params.require(:meter).permit(:reading)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutomaticRobot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meters/_form.html.erb
<%= form_for(@meter) do |f| %>
  <% if @meter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meter.errors.count, "error") %> prohibited this meter from being saved:</h2>

      <ul>
      <% @meter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reading %><br>
    <%= f.text_field :reading %>
  </div>
  <div class="field">
    <%= f.input :img, as: :file, accept: 'image/png'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meters/edit.html.erb
<h1>Editing Meter</h1>

<%= render 'form' %>

<%= link_to 'Show', @meter %> |
<%= link_to 'Back', meters_path %>

app/views/meters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meters</h1>

<table>
  <thead>
    <tr>
      <th>Reading</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meters.each do |meter| %>
      <tr>
        <td><%= meter.reading %></td>
        <td><%= link_to 'Show', meter %></td>
        <td><%= link_to 'Edit', edit_meter_path(meter) %></td>
        <td><%= link_to 'Destroy', meter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meter', new_meter_path %>

app/views/meters/new.html.erb
<h1>New Meter</h1>

<%= render 'form' %>

<%= link_to 'Back', meters_path %>

app/views/meters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reading:</strong>
  <%= @meter.reading %>
</p>

<%= link_to 'Edit', edit_meter_path(@meter) %> |
<%= link_to 'Back', meters_path %>